### ISSUE TITLE
Add RFCs in Composer's keywords

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Json#4]
Related to https://github.com/hoaproject/Http/pull/9#issuecomment-63208329.

**Comment by Jir4** [comment]
Still revelant ?

**Comment by Hywan** [comment]
Yup!

**Comment by shulard** [comment]
Hello, 
seems that RFCs are already in the `composer.json` file `RFC4627` and `RFC7159`. I think this issue can be closed 😄.
